import { createFileRoute } from "@tanstack/react-router";
import { LegalLayout } from "@/components/LegalLayout";
import { ChevronDown } from "lucide-react";

export const Route = createFileRoute("/faq")({
  head: () => ({
    meta: [
      { title: "FAQ — FullPlay" },
      { name: "description", content: "Answers to common questions about FullPlay deposits, withdrawals, KYC, bonuses, referrals, fairness, and support." },
    ],
  }),
  component: FaqPage,
});

type QA = { q: string; a: string };

function Accordion({ items }: { items: QA[] }) {
  return (
    <div className="not-prose space-y-2">
      {items.map((it) => (
        <details key={it.q} className="group rounded-xl border border-border bg-surface-2 px-4 py-3 open:border-primary/50 transition">
          <summary className="flex items-center justify-between gap-3 cursor-pointer list-none">
            <span className="text-sm font-semibold text-foreground">{it.q}</span>
            <ChevronDown className="w-4 h-4 text-primary shrink-0 transition-transform group-open:rotate-180" />
          </summary>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{it.a}</p>
        </details>
      ))}
    </div>
  );
}

function FaqPage() {
  const cat = (items: QA[]) => <Accordion items={items} />;

  const sections = [
    { id: "deposits", title: "Deposits", body: cat([
      { q: "What is the minimum deposit?", a: "₹100 via UPI, net banking, or supported cards." },
      { q: "How long do deposits take?", a: "UPI is instant. Cards and net banking usually credit within 60 seconds." },
      { q: "Are there deposit fees?", a: "FullPlay charges zero deposit fees. Your bank may apply their own charges." },
    ])},
    { id: "withdrawals", title: "Withdrawals", body: cat([
      { q: "When can I withdraw?", a: "Anytime after completing KYC. Minimum withdrawal is ₹500." },
      { q: "How fast are payouts?", a: "UPI withdrawals are typically processed within minutes; bank transfers within 24 hours." },
      { q: "Why was my withdrawal rejected?", a: "The most common reason is incomplete KYC or mismatched bank details. Check your profile and resubmit." },
    ])},
    { id: "kyc", title: "KYC Verification", body: cat([
      { q: "What documents are accepted?", a: "Aadhaar, PAN, Passport, or Driving License — plus a recent address proof if requested." },
      { q: "How long does KYC take?", a: "Most submissions are verified within 24 hours; many are instant." },
      { q: "Is my data safe?", a: "Yes — documents are encrypted with AES-256 and only accessed by authorised KYC staff." },
    ])},
    { id: "bonuses", title: "Bonuses", body: cat([
      { q: "What is the welcome bonus?", a: "100% on your first deposit up to ₹10,000, with a 35x wagering requirement." },
      { q: "Can I have multiple active bonuses?", a: "No — only one bonus may be active at a time. Finish or cancel one to claim another." },
      { q: "Why was my bonus removed?", a: "Bonuses can be voided for breaching terms such as exceeding the max bet cap (₹200/round)." },
    ])},
    { id: "referral", title: "Referral Rewards", body: cat([
      { q: "How much can I earn?", a: "Up to 25% revenue share on your referred players' net gaming activity, paid weekly." },
      { q: "Where do I find my link?", a: "Open the side menu → Referral Program. Your link and stats are on that page." },
      { q: "Do self-referrals count?", a: "No — fake or self-referred accounts void all rewards." },
    ])},
    { id: "account", title: "Account Issues", body: cat([
      { q: "I forgot my password.", a: "Use 'Forgot password' on the login page. A reset link is emailed within seconds." },
      { q: "How do I change my email?", a: "Open Profile → Security. Email changes require re-verification." },
      { q: "Can I delete my account?", a: "Yes — contact support@fullplay.app from your registered email. Withdraw your balance first." },
    ])},
    { id: "fairness", title: "Game Fairness", body: cat([
      { q: "Are FullPlay games fair?", a: "All games are provably fair — every outcome is generated by a verifiable seed you can check after each round." },
      { q: "What's the RTP?", a: "Most games run between 96% and 99% RTP. Each game shows its own RTP in the rules tab." },
    ])},
    { id: "support", title: "Support Timing", body: cat([
      { q: "When is support available?", a: "24/7, 365 days a year. No exceptions." },
      { q: "How fast do you reply?", a: "Live chat: under 2 minutes on average. Email: within an hour." },
    ])},
  ];

  return (
    <LegalLayout
      eyebrow="HELP"
      title="Frequently Asked Questions"
      intro="Quick answers to the questions players ask most. Tap any question to expand."
      updated="May 24, 2026"
      sections={sections}
      logoSizeClassName="h-14 w-14"
      logoGapClassName="gap-0"
      logoTextClassName="text-xl sm:text-2xl -ml-0.5 sm:-ml-1"
    />
  );
}